services:
  database:
    build:
      context: ./mongodb
    container_name: mongo_database
    ports:
      - "27017:27017"
      
  backend:
    build:
      context: ./app
    ports:
      - "5000:5000"
    depends_on:
      - database
      - redis_cache
      - rabbitmq
      
  redis_cache:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    ports:
      - "80:80"
  
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
